[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "atriumn-ai-sdk"
version = "0.1.0"
description = "Python SDK for Atriumn MCP APIs"
authors = [{name = "Atriumn Team", email = "support@atriumn.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "httpx>=0.24.0",
    "pydantic>=2.0.0",
]

[project.urls]
Homepage = "https://github.com/atriumn/atriumn-sdk-python"
Repository = "https://github.com/atriumn/atriumn-sdk-python.git"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
]